# https://github.com/behaviorbot/welcome
---
# https://github.com/behaviorbot/new-issue-welcome
newIssueWelcomeComment: >
  Thanks for opening your first issue here!
# https://github.com/behaviorbot/new-pr-welcome
newPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.
# https://github.com/behaviorbot/first-pr-merge
firstPRMergeComment: >
  Congrats on merging your first pull request! Your contribution is highly appriciated!
